### PR TITLE
Use codes_ui version 1.2.7 from its own download page

### PR DESCRIPTION
**Pull request by iainrussell**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by iainrussell** [comment]
@conda-forge-admin, please rerender

**Comment by dtip** [comment]
Hi @iainrussell - the error looks to be:
```
CMake Error at CMakeLists.txt:984 (file):
  file COPY cannot find
  "D:/bld/codes-ui_1570784083862/work/scripts/codes_ui.bat".
```

**Comment by iainrussell** [comment]
Hi @dtip, thanks for that, I think I missed that message. I thought the
problem was a Qt 5.12.5 issue that affects Linux. Sorry you're getting
spammed with messages! I'm making little tweaks to the config as a
background task as I'm working on other things!

**Comment by dtip** [comment]
Build is working - fantastic!

**Comment by iainrussell** [comment]
Thanks @dtip for merging!  Nice to have the green lights again!

**Pull request merged**
